export const SCREENS = {
  HEALTH: '/health/ping',
  LOGIN: '/login',
  REGISTER: '/register',
  REGISTER_SUCCESS: '/registerSucess',
  INFO_USER: '/info-user',
  AUTH: '/auth',
  IDAUTH: '/idauth',
  FACEAUTH: '/faceauth',
  IDENTIFICATION: '/identification',
  RESULT_OCR: '/result-ocr',
  RESULT_EKYC: '/result-ekyc',
  VERIFYINFOUSER: '/verifyinfouser',
  AUTHERRORREPORT: '/authErrorReport',
  SUCCESSSENT: '/successSentScreen',
  IDENTIFICATIONAPPROVE: '/identificationApprove',
  IDENTIFICATIONDEFINITION: '/identificationDefinition',
  EIDENTIFICATIONDEFINITION: '/eIdentificationDefinition',
  EKYC_SCREEN: '/ekyc',
  EKYC_INTRODUCTION: '/ekycIntroduction',
  EKYC_GUIDE: '/ekycGuide',
  ECONTRACTCONCEPT: '/econtractConcept',
  ECONTRACTINFO: '/econtractInfo',
  ECONTRACTVIEWER: '/econtractViewer',
  ECONTRACTOTPAUTH: '/econtractOtpAuth',
  ECONTRACTOTPSUCCESS: '/econtractOTPSuccess',
  ECONTRACTSUCCESS: '/econtractSuccess',
  ECONTRACTFAIL: '/econtractFail',
  ECONTRACTDEFINITION: '/econtractDefinition',
  BNPL_INTRODUCTION: '/bnplIntroduction',
  // Phiên đăng nhập hết hạn
  SESSION_EXPIRED_SCREEN: '/session-expired'
};
